export const EXERCISE_IMAGES = {
  ["Bench Press"]: "/Strength/Bench Press.jpg",
  ["Tricep Dips"]: "/Strength/Tricep Dips.jpg",
  ["Running (Treadmill)"]: "/Cardio/Running (Treadmill).jpg",
  ["Pull-Ups"]: "/Strength/Pull-Ups.jpg",
  ["Bent-Over Barbell Rows"]: "/Strength/Bent-Over Barbell Rows.jpg",
  ["Cycling (Stationary Bike)"]: "/Cardio/Cycling (Stationary Bike).jpg",
  ["Squats"]: "/Strength/Squats.jpg",
  ["Lunges"]: "/Strength/Lunges.jpg",
  ["Rowing Machine"]: "/Cardio/Rowing Machine.jpg",
  ["Military Press"]: "/Strength/Military Press.jpg",
  ["Lateral Raises"]: "/Strength/Lateral Raises.jpg",
  ["Elliptical Trainer"]:"/Cardio/Elliptical Trainer.jpg",
  ["Deadlifts"]: "/Strength/Deadlifts.jpg",
  ["Seated Cable Rows"]: "/Strength/Seated Cable Rows.jpg",
  ["Jump Rope"]: "/Cardio/Jump Rope.jpg",
  ["Dumbbell Curls"]: "/Strength/Dumbbell Curls.jpg",
  ["Hammer Curls"]: "/Strength/Hammer Curls.jpg",
  ["Preacher Curls"]: "/Strength/Preacher Curls.jpg",
  ["Concentration Curls"]: "/Strength/Concentration Curls.jpg",
  ["Cable Curls"]: "/Strength/Cable Curls.jpg",
  ["Tricep Pushdowns"]: "/Strength/Tricep Pushdowns.jpg",
  ["Overhead Tricep Extensions"]: "/Strength/Overhead Tricep Extensions.jpg",
  ["Close-Grip Bench Press"]: "/Strength/Close-Grip Bench Press.jpg",
  ["Kickbacks"]: "/Strength/Kickbacks.jpg",
  ["Leg Press"]: "/Strength/Leg Press.jpg",
  ["Leg Curls"]: "/Strength/Leg Curls.jpg",
  ["Leg Extensions"]: "/Strength/Leg Extensions.jpg",
  ["Calf Raises"]: "/Strength/Calf Raises.jpg",
  ["Crunches"]: "/Strength/Crunches.jpg",
  ["Planks"]: "/Strength/Planks.jpg",
  ["Russian Twists"]: "/Strength/Russian Twists.jpg",
  ["Leg Raises"]: "/Strength/Leg Raises.jpg",
  ["Bicycle Crunches"]: "/Strength/Bicycle Crunches.jpg",
  ["Mountain Climbers"]: "/Strength/Mountain Climbers.jpg",
  ["Burpees"]: "/Strength/Burpees.jpg",
  ["Kettlebell Swings"]: "/Strength/Kettlebell Swings.jpg",
  ["Clean and Press"]: "/Strength/Clean and Press.jpg",
  ["Snatches"]: "/Strength/Snatches.jpg",
  ["Farmer's Walk"]: "/Strength/Farmer's Walk.jpg",
  ["Lat Pulldowns"]: "/Strength/Lat Pulldowns.jpg",
  ["Dumbbell Rows"]: "/Strength/Dumbbell Rows.jpg",
  ["T-Bar Rows"]: "/Strength/T-Bar Rows.jpg",
  ["Front Raises"]: "/Strength/Front Raises.jpg",
  ["Rear Delt Flyes"]: "/Strength/Rear Delt Flyes.jpg",
  ["Upright Rows"]: "/Strength/Upright Rows.jpg",
  ["Skull Crushers"]: "/Strength/Skull Crushers.jpg",
  ["Arnold Press"]: "/Strength/Arnold Press.jpg",
  ["Barbell Curls"]: "/Strength/Barbell Curls.jpg",
  ["Stair Climber"]: "/Cardio/Stair Climber.jpg",
  ["Dumbbell Shoulder Press"]: "/Strength/Dumbbell Shoulder Press.jpg",
  ["Chest Dips"]: "/Strength/Chest Dips.jpg",
  ["Cable Crossovers"]: "/Strength/Cable Crossovers.jpg",
  ["Incline Bench Press"]: "/Strength/Incline Bench Press.jpg",
  ["Decline Bench Press"]: "/Strength/Decline Bench Press.jpg",
  ["Dumbbell Flyes"]: "/Strength/Dumbbell Flyes.jpg"
};